install.packages("MASS")
install.packages("momentchi2")
install.packages("kpcalg")
install.packages("usethis")
install.packages("pcalg")
install.packages("devtools")
install.packages("BiocManager")
BiocManager::install("RBGL")
BiocManager::install("graph")
devtools::install_github("Diviyan-Kalainathan/RCIT", force=T)
library(kpcalg)
library(pcalg)
library(devtools)
library(RCIT)

RCIT(rnorm(1000),rnorm(1000),rnorm(1000))
RCoT(rnorm(1000),rnorm(1000),rnorm(1000))
